### ISSUE TITLE
Multiple Streams using AioQuic

### ISSUE THREAD

**Issue by devkdas** [michealroberts/usethis#5]
hai ,

It is not an issue.
one small quick query

@michealroberts 
Could you please confirm were you able to create multiple streams in a single connection using the AIOQUIC code .

Sorry for raising an issue as i am unable to find your email to ask this query.

Looking forward for your reply

Thank you.

**Comment by michealroberts** [comment]
@Karthikdasari0423 Hi Karthik, I'm not quite sure you have the right person of repository for this question!

I'll close this issue now. Thank you.

**Comment by devkdas** [comment]
Hi @michealroberts 

I think you have used aioquic right.

Could you please confirm were you able to create multiple streams in a single connection using the AIOQUIC code .

Thank you.
